{% set name = "django-anymail" %}
{% set version = "1.3" %}
{% set sha256 = "6868f65ea15ea958591aecf222ddc3cf37970ca5441a035ddac285168720ed52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - django >=1.8
    - requests >=2.4.3
    - six

about:
  home: https://github.com/anymail/django-anymail
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Django email backends and webhooks for Mailgun, Mailjet, Postmark, SendGrid, SparkPost and more '
  description: |
    Anymail integrates several transactional email service providers (ESPs) into Django, with a consistent API that lets you use ESP-added features without locking your code to a particular ESP.
    It currently fully supports Mailgun, Mailjet, Postmark, SendGrid, and SparkPost, and has limited support for Mandrill.
  doc_url: https://anymail.readthedocs.io/en/stable/
  dev_url: https://github.com/anymail/django-anymail

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
