travis:
  secure:
    BINSTAR_TOKEN: jQ06emhEhG80fgamyqn8nhRra16XmAk/3XQkbedf24vc8mRe3ISCPXnjmDeSwCvofl6QzpHNpWTkh2XW2TP99d5kAKihJSnTEyS4jtiRD/NwJtqTUpc1JDGhmey4JLbNTK81iBvk7vwOmYWo5aJPXSruqB88SYsRXsyJ1qc2KfZKIvTQEq6tW9npk8xHtpPYURkg+Fg10jYJxN3L0FBnzmIlsagJTxeLaChcGf9LnV/ChTjO5MY0DG1csZx2s9MLci1LgxCQMGT0PBMxNVeb3FVN5T5vu1ewniwM9m9Jn8SWtkmt+YHlHZUxbar9DLEi3Td2Rc9isPwdTlJRpz5rDRfDHfHMdtY26odIuANt1QMyNDLJd6/zjEoKpdjY3rPK2rf/kKqkoVInPUOG50TAH2zkSc6KSm6GB8/KtxJytRD132OgQt87c9wGV1Vqz2nRsCA/jaG7AdYMAuCF4VqBG0epnV78iUFzFWmdhrMHasLTU9qkW13CzgPlVVUBsR42YWKJeOfjOn9vmtt0UrudDEy4m7DjOR1eom2wMPB+xILL50Kzy3v1d5ZC0uZ8mVN+I/4w+fqQshz80a6kXq5XQoRBSXFCBLiQXwjELCaj2QNP2w5Dmw5vfHwKhpIpl5frX/qT5hY7ZSqV43UiFSFebtcno6BBvwlexprIHh1fjVQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
