travis:
  secure:
    BINSTAR_TOKEN: nv3cE+O7gzgnwKD2X0bGM78oWZtHVfbiPp4IDBf5AkCfbORooO1o4UtXAXSJOS8+3unl9Xo9Q4EUY+TJsu69lFLhAyZqxFAf1xv61nx1HVNcfudqzp9L9zu25biPAPgI6ih2CDxyMFReg7esqjTIuc1EOYJHaGIUAvHz+AOJt0QEQZCQ4HozsXygnVOIGc2wpJ3+YbdT6blQj+5fLnDi0q9u5axoYOa2FVZDpJh8BBiJUesuO0roR+8pwFPvzHG5DbO+9db37CK6uDUnaNtcfhl4ZxqIJHdaR8cxfN8e5RjtmhBkS8FTK7LAoXim6fjpW9CCSxbQohN8TAoKvvxuEHu30OgbGwcIzqaYlXITIGtxHnhA9U/g9VFYVeYxOAoAMb3fzu/ESfv4Ego9nTDQGRaMlVUe5UqmO/8P+O5jkSZE25Au3w2/QslQpo65WXyLG6e0uuaYoYP6CK1FN7BobIe+bpwDQljAbqI4nOo1C4MdrrlI1/isiAarZCUIozirXOtxVsuh9dHWNkOYdPYYvcDDiu1ktqNCxPvZb8h/debPWaDY1JSqbDFGGDmZyMsEM7W46ABf+e9av2khxKawSOLnybroj3O4/+HRTn5/CJpr2jpBNdws9oeoKk96n4CRAaFgJl1p47GCd/V0yRmqEfDl9Z1jD41GyI0L9AbSWEw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
