travis:
  secure:
    BINSTAR_TOKEN: H3bVa3oAVzkw5tLtMf6QLgtr5LfnuOMxYVJ3b05INFMXfz8yy12VZlnnEV8zunlxKyZ9LRYV+2qjByW/i0F3tpkIzZGUE6dgxK6iAyzWq3LtN9ZVWFeDkDpKhvTkAqFrgsCm5YIU6ZLZpNlL2o1FUer3miDFajQCOjQ1Lob5wY/FxjfeD93V1g1fps0FNtu6wI2fyKnAgqnUfNGZkfro0xXUkfbUX0kH5oZqxxYZfGrMOHdACsHLq43cvAl2YWFP/+e8a8Tj9wRo0MBGZsE6ptIhD/rwWiVftvlU80aYvatEDbFqx/sb+u+6tY7UvpZRZ/Zz3B7/dJ59Bn4HYQVz6FALXEhtiUI2PVlTpYkDdJuXh9vj+DdjBBPVULbe/tdt4ONORE9rJu8WXvOTXP0rnKDITheoDekulPhzT1blDGe62edglPpHfAysXHFGcJfwZJpxmz05udIljnJJEslJuZglLQWm/9wIjdNE2rNxmRgcgNpzLt0zaXNQi9UpRKD9/2gqUBMU0/wQPOvCFgRfgOfmyplKS9EEpAXCQ5kEsDGpoRvF1TXfNVskwMnfgJ96l6K2pj/tM14SlBEAGp4H6rLzU6v4dW0VDYdCVZEyaXIeJ3kFAasC50qrdFnjgB+cmzHLzcA+938d6RZKzLBNFPNm7Dk6keWAJyccSYq4SII=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
